### ISSUE TITLE
Loading raw traces from Neurophotometrics

### ISSUE THREAD

**Issue by gavinscott280** [djamesbarker/pMAT#4]
Hi there,

I'm attempting to load traces from the Neurophotometrics system contained in .csv files. I am able to get as far as the dialogue box that requests user input for start and end buffers, but after clicking OK, the program either reopens the directory window to select files or does nothing.

The .csvs are arranged as follows:
Column 1: FrameCounter
Column 2: Timestamp
Column 3: Flags
Column 4: the data channel containing the raw trace

I should also add that for each animal/recording, the GCamP channel and control channel are in separate .csv files.

Thanks in advance for your assistance,
Gavin

**Comment by djamesbarker** [comment]
Hi Gavin,

   Can you tell me what your 'Flags' Column is? Also, for your neurophotometrics data, can you guarantee that the first timestamp is the GCAMP/signal channel? Feel free to send me a sample file by email so that we can work towards including the neurophotometrics signal (contact @ www dot thebarkerlab dot com).

   We're in the process of revising the preprint for a paper and releasing the next version of pMAT. Somewhere after this release, the next goal is the inclusion of other loading engines, including one for Neurophotometrics native data format.  For now, your format needs to match the format of the CSV files in the sample data folder. The format is as follows:

File 1- Fiber Photometry
Column 1: Timestamps
Column 2: Signal channel
Column 3: Control channel

File 2- Behavior
Column 1- Event name
Column 2- Onset time for event
Column 3- Offset time for event.

The offset times arent currently used, so if you don't have offset times for experimental events, then you might just re-paste the onset times twice.

  David

**Comment by gavinscott280** [comment]
Hi David,

Thanks very much for your quick response!

The "flags" column is just a constant value that remains the same throughout the recording. We have just begun using this system and honestly still haven't been to determine what it means.

I've sent you an email with sample data and the errors that Matlab is throwing.

Thanks again!
Gavin
