### ISSUE TITLE
Issue exporting Trial Trace Data

### ISSUE THREAD

**Issue by Ori91** [djamesbarker/pMAT#7]
Hi,
When exporting Trial Trace Data with a batch of trials, I don't get the same numbers of values per trial as I should. Especifically, from "TrialData_15" zscored values are missing for many of the trials. 
However, if exporting the Trial Trace Data single trial by single trial, calcium data are complete (but it's very laborious and time consuming).

Do you have any idea of why this is hapenning and how to fix the issue?
Thanks

**Comment by djamesbarker** [comment]
Hi Ori,

  I don't quite understand the issue you are having, but this could relate
to your trials overlapping in time.

   pMAT does not allow data to be represented twice,  so if your PETH
window is 20 seconds (-10 to +10), and you have a trial that is within 20
seconds on the prior trial, then it will omit a trial rather than allowing
the overlap. There are many reasons for this, but this is the most likely
scenario.

 David

**Comment by Ori91** [comment]
Hi David,

I indeed observe that trials are omitted if they overlap but this is not exactly my issue.
You can see on the image I attached that data are missing from TrialData_15 until TrialData_'end' for some trials (here, line 2, 8, 13, 15 etc) and this independently of the PETH window.

![TrialTraceData](https://user-images.githubusercontent.com/86053528/122757518-0246fa00-d298-11eb-901d-e5307084ef28.JPG)

**Comment by djamesbarker** [comment]
Hi Ori,

  This is the first I've seen of this. Can you reach out via email so that I can try to get an example data file to try and track this down?
  
   David

**Comment by djamesbarker** [comment]
This issue was determined to be either a problem with the CSV import format or the excel readout of that format and not a pMAT issue. Closing this now.

David
